title: Visual Analytics Final Project
description: The research group formed by teachers Angela Maria Rojas and Elvia Esther Vargas, who belong to the Psychology Department of the Universidad de los Andes, wishes to achieve an understanding and use of the data collected during the last 3 years of the Massive Open Online Course "Sexuality ... much more than sex" provided by the Coursera platform, in order to verify the effectiveness of the online course. This project illustrates the way in which the problem was approached from a perspective of the Visual Analytics field, generating great value to the research group.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
